branches:
  only:
      - master

environment:
  matrix:
    - TARGET: nightly-x86_64-pc-windows-msvc

cache:
  - server\target
  - C:\Users\appveyor\.cargo\registry

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV
  - cd server

build: false
test_script:
  - cargo test --all
